# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderslab', '0004_auto_20171128_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 12, 17, 9, 527038)),
        ),
    ]
