# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderslab', '0005_auto_20171201_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 15, 52, 3, 313936)),
        ),
    ]
